server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/biblioteca}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:biblioteca}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:biblioteca123}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect